### ISSUE TITLE
Critical typo in readme

### ISSUE THREAD

**Issue by JustinWomack** [burl/node-py-marshal#3]
From the readme: 

> Or, for reading a buffer of concatenated marshaled objects, you can create a decoder and call the read method until the buffer is exhausted:
> 
> const PyMarshal = require('py-marshal');
> 
> // however you manage to get a buffer...
> const buffer = GetABufferOfMarshaledDataSomehow();
> const decoder = new PyMarshal(buffer);
> 
> **while(decoder.MoreData)** {
>   const obj = decoder.read();
>   DoSomethignWithData(obj); // use your data...
> }

The 'M' on MoreData should instead be lowercase. Should be:

> **while(decoder.moreData)**

**Comment by burl** [comment]
fixed
